# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a189850df38ac9b45a18e205afbc539597ed3d049c65b23b9f9dba9fb2dc79860b14d200dafcc8593f2588e87698939a663af84d743d22fae03431604239064

test:
  secret_key_base: 561d2cd91986dff6350ee20c8e559c7ea100168f4c6e4b17c26a21f772f5d9d2f7f1d95a15ddf170be50e0ee6014dc3e6bb342290510922b627c1e7e48a9d39b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
